\newpage

# 摘要

**摘要**

台湾作为典型的岛屿型经济，全岛约七成面积是山地和丘陵，漫长的中央山脉横断东西，在很长的一段时间内交通不便，必要的生产资料与产出品难以自给自足，于是对外贸易就成为台湾经济发展的命脉。自从第二次世界大战结束台湾光复开始，台湾经济经历了几十年的快速增长，缔造“台湾奇迹”，称为“亚洲四小龙”成员。从对外出口的内容上看，台湾拥有丰富的尖端制造业，在半导体、通信、电子精密制造等方面具有突出领先的地位，主要通过高科技产业出口赚取外汇。从对外出口的方向上看，伴随着台湾经济结构从劳动密集型到资本密集型和人力技术密集型的转变，台湾的进出口重心经历了从美国与日本到中国大陆和东盟国家的转移，尤其是中国大陆改革开放之后对台湾展现出强大的“群聚效应”，令台湾当局忧心忡忡，多次祭出试图引导台商将中国大陆的进出口及投资份额向东南亚国家转移的“南向政策”与“新南向政策”，意图在一定程度上影响台湾进出口及投资的既有格局，并扩张台湾在东南亚地区的“政治影响力”。这种试图使用政治手段干涉经济的行为不仅与客观经济规律相背离，也无益于两岸关系的健康发展与陆台人民的友好交流。

基于这种现状，我们利用1990-2019年台湾进出口贸易与对外直接投资等数据，运用双重差分法对台湾地区两次南向政策的实施效果进行了实证研究。结果表明：李登辉当局提出的“南向政策”与蔡英文当局提出的"新南向政策"对台湾进出口及对外直接投资的比重分布没有作用，并且南向政策与新南向政策的实施，对于台湾进出口及对外直接投资的比重亦没有正向的滞后效应。尽管南向经济为台湾提供了新的经济发展思路，但在经济上试图脱离中国大陆对台湾经济的影响无异于作茧自缚。台湾当局应审时度势，加强与祖国大陆的经济文化交流，推动两岸经贸关系和谐发展。

**关键词**

南向政策；双重差分法; 事件研究法；台湾贸易

\newpage

**Abstract**

As a typical island economy, Taiwan has about 70% of the island's area covered by mountains and hills, and it is difficult to be self-sufficient in the necessary means of production and products. Therefore, foreign trade has become the lifeblood of Taiwan's economic development. Since the recovery of Taiwan after the end of World War II, Taiwan's economy has experienced decades of rapid growth, creating a "Taiwan miracle" and ranking among the four Asian dragons. From the perspective of the content of foreign exports, Taiwan has a rich and cutting-edge manufacturing industry, with a prominent leading position in semiconductor, communications, electronic precision manufacturing, and other aspects. It mainly earns foreign exchange through high-tech industry exports. From the perspective of export direction, with the transformation of Taiwan's economic structure from labor-intensive to capital intensive and technology intensive, Taiwan's import and export focus has shifted from the United States and Japan to Chinese Mainland and ASEAN countries. In particular, Chinese Mainland has shown a strong "clustering effect" on Taiwan after its reform and opening up, which worries the Taiwan authorities, The "southward policy" and "new southward policy" that try to guide Taiwanese businessmen to transfer the import, export and investment share of Chinese Mainland to Southeast Asian countries are intended to affect the existing pattern of Taiwan's import, export and investment to a certain extent, and expand Taiwan's "political influence" in Southeast Asia. This attempt to use political means to interfere in the economy not only deviates from objective economic laws, but also is not conducive to the healthy development of cross-strait relations and friendly exchanges between the mainland and Taiwan people.



Based on this situation, we used Taiwan's import and export trade and foreign direct investment data from 1990 to 2019 to conduct an empirical study on the implementation effect of the two southward policies in Taiwan using the dual difference method. The results show that the "southward policy" proposed by Lee Teng hui and the "new southward policy" proposed by Tsai Ing-wen have no effect on the proportion distribution of Taiwan's imports, exports, and foreign direct investment, and the implementation of the southward policy and the new southward policy has no positive lag effect on the proportion of Taiwan's imports, exports, and investment. Although the southward economy has provided new ideas for Taiwan's economic development, trying to break away from Chinese Mainland's economic development in Taiwan is tantamount to tying oneself in a cocoon. The Taiwan authorities should assess the situation, strengthen economic and cultural exchanges with the mainland, and promote the harmonious development of cross-strait economic and trade relations.

**Key Words**

"Go South Policy", difference in differences, event study method, Taiwan's trade
