# 绪论

## 研究背景及意义

### 研究背景

1987年，台湾地区前“行政院长”孙运璿接受天下杂志专访。对于近年来台湾对大陆探亲政策的开放，工商业界也希望当局能逐渐开放前往大陆投资的渠道，使转口贸易增加。他就通商与投资方面，表达了自己的看法，认为台湾须谨慎应对大陆的通商与通航需求，避免在经济上过度依赖大陆[@孫運璿]。

此时，对于台湾贸易与投资的未来发展方向，形成了“西进”与“南向”两个派别。西进派主张拥抱大陆改革开放的新趋势，将台湾未来经济发展的重心向中国大陆靠拢，以此促进台湾经济的发展。南向派则希望利用东南亚国家巨大的潜在需求，加强台湾对东南亚国家的贸易与投资，避免台湾经济过分依赖某一单一经济体[@刘荣茂2005南向政策]。

随着台湾当局逐渐放开两岸贸易和投资限制，台商之间形成西进大陆的“磁吸效应”，创造出台商群体的“西进潮流”。针对日益密切的两岸经贸关系，台湾当局担心两岸经贸依存度的提升将造成自身有关"安全保障"的危险[@舒萍1999台湾当局的]。为了应对西进潮流，当局推出名为“根留台湾”的政策及相应措施，希望以台湾为中心，将产业垂直分工中高附加值的研发、设计等部门留在台湾，将低附加值的加工、装配等部门转移岛外。通过塑造根留台湾的垂直分工体系，放缓台商西进中国大陆的速度[@刘荣茂2005南向政策]。

1988年，蒋经国于其任内意外病逝，根据台湾相关法律，李登辉继任。李登辉任期中，政治上结束了两蒋时期的“动员戡乱”条款，加速宪政化，并力图实现“台湾政权台湾化”。经济上则谋划推行基于台湾本土的收缩性政策，力图使经济服从于政治，将对大陆的经济政策与政治政策统一起来。1996年，李登辉在“全国经营者大会”提出“戒急用忍^[“戒急用忍”原为满清康熙帝赐予皇子胤禛的座右铭。]”的经济方针，劝阻台商“步子不要太快，必要时应多踩刹车”，避开大陆经济锋芒才能“行稳致远”[@舒萍1999台湾当局的]。

“戒急用忍”方针贯穿了李登辉执政的整个时期，并实质成为了台湾当局推出“南向政策”的指导思想。1993年，台湾当局为分散岛内厂商海外投资地区，并希望激发东南亚地区的发展潜力，同时为解决“区域边缘化之疑虑”、“台湾运营风险”以及“台商函盼政府伸出援手”等问题，开始构思以东南亚国家为主要经贸拓展对象的方案。当年台湾"经济部"设立“南向专案小组”，成立“亚洲台湾商会联合总会”，并由李登辉提出《南进政策说帖》。1993年年底，台湾通过了《加强对东南亚地区经贸工作纲领》，正式开启南向政策。南向政策是一系列外交及经济政策的统称，其目的在于推动台商的海外投资方向向东南亚转移，并使用经济力量为台湾地区扩张一定的政治影响力，减少对大陆的经济依赖[@刘青建2008对台湾]。此后，此阶段南向政策经过前后两次延长，至2002年年底为止。

南向政策后期，恰逢东南亚金融危机，台湾经济产业界要求松绑“戒急用忍”的声音与日俱增。陈水扁于2000年宣布要将“戒急用忍”的政策逐步替换为“积极开放，有效管理”的新路线[@bing2017taiwan]。尽管如此，陈水扁政府为适应台湾加入世贸组织及东盟自贸区成立的经济形势改变，还是重启了南向政策，但收效甚微，政府及媒体对此也甚少提及，到马英九执政时期已名存实亡，政治意涵大幅减少[@黄奎博]。

2015年，时任民进党主席的蔡英文宣布民进党在未来执政后将推动“新南向政策”。在此前的台湾地区领导人选举中，新南向政策是民进党阵营的一项重要政见。蔡英文表示过去李登辉政府推行的南向政策旨在引导台湾企业在东南亚地区的投资，基于该政策，未来民进党政府将进行持续推进。[@盛九元2016蔡英文的]指出，新南向政策的核心，仍是进一步强化与东盟国家关系、降低对中国大陆的经济依赖、减少大陆对台湾人才及资源的磁吸效应和保证台湾的“安全”。对此政策，蔡英文当局制定了“四大主轴”、“五大旗舰计划”、“三大潜力领域”。通过与“新南向”国家建立多个维度的合作关系，将经贸合作方面的利益转化为“外交利基”[@李鸿阶2019台湾当局]。

台湾是海岛型经济体，存在着自然资源缺乏与消费市场狭小等“先天性不足”，也存在岛内经济发展强依赖外贸经济和区域经济边缘化等“后天性难题”。凭借自身自给自足难以实现持续的经济增长，外贸与经济增长密切相关，对外出口则相关程度最高，是重要的经济命脉[@李非2009台湾经济发展规律探析]。从二十世纪五十年代开始，美国和日本是台湾地区前两大贸易伙伴。但从二十一世纪开始，中国大陆经济崛起，使台湾的贸易重心逐渐转移到了中国大陆。2008年，随着台湾地区第二次政党轮替，中国国民党重新执政，台湾与大陆签订了《海峡两岸经济合作框架协议》，进一步增进了海峡两岸的“三通^[指通商、通航、通邮。]”，促进了两岸的贸易与投资。如今，大陆已经成为台湾的最大贸易伙伴，至2018年台湾对大陆出口值已逾900亿美元，年增速接近10%。自李登辉政府至蔡英文政府，南向政策多次被台湾当局提出，并搭配相应的配套政策，其设置的目的都有关经济与政治两个维度，而且进行了实质性的预算支援。但在台湾经济经历“亚洲四小龙”奇迹之后，就再难见到彼时的蓬勃发展。随着中国大陆经济实力与日俱增，海峡两岸经贸关系稳步提升，区域经济一体化的潮流不可阻挡，这不禁让我们疑问：以远离大陆政治导向驱动的南向政策，是否有利于台湾的经济发展？南向，是否是有利台湾经济的正确发展方向？

### 概念界定

针对“投资”的概念解释。投资指一定数量的资本，为了一定的目的，往一定的地区和一定的经营项目的投入，表现为厂商为购买新的资本物而进行的支出。从资本输出地流到输入地，通常有两种形式：一种是直接投资，一种是间接投资。历史上，台湾地区对海外投资的种类既有直接投资，也有间接投资。由于数据完整性的原因，本研究主要的研究对象是直接投资。

### 研究思路和研究方法

**1. 文献综述法**

本论文基于已有有关台湾新旧南向政策的文献进行研究，参考范围有中英文的相关论文、杂志期刊、报纸新闻、书籍文献等。本文从近代台湾贸易的历史出发，通过文献对东盟历史以及南向政策及新南向的相关资料的整理与提炼，从中找出相关的知识要点，列出论文撰写的大纲提要，最终得出有价值的观点与看法。

**2. 比较分析法**

在新南向政策实施之前，台湾当局已经推行了数波南向政策，南向政策与新南向政策的实施既有相同点又有不同点，在本论文你的撰写中比较了二者的异同，对南向政策和新南向政策进行分析的同时挖掘了新旧政策的区别与联系。

**3. 历史分析法**

本文从台湾近代贸易的历史研究出发，详细陈述了国民政府迁台以来台湾对外经贸投资的发展历史以及台湾贸易产业结构如何从进口替代型转变为出口扩张型，最终对台湾南向政策以及新南向政策成因的历史背景也做了详细的分析。

**4. 数据分析法**

本文在撰写的过程中使用了表格、图形等方式对统计量进行展示，其中涉及时间序列图形、热力地图、函数图像、数学模型等诸多表达类型，最后使用了计量统计模型对论题进行严密的论证，保证了论文结论的科学性。

### 分析框架

本文共分为五个章节。

第一章为绪论。这一章主要介绍研究背景与研究意义，介绍了南向政策与新南向政策相关的历史背景，进行文献综述，对学界现有的文献研究进行概述，总结研究状况。最后总结了论文创新点与不足之处。

第二章为背景研究。这一章主要梳理了二战前后台湾对外贸易的历史背景，包括二战前后台湾贸易的起步发展，冷战期间台湾对外出口贸易发展的路径变化以及台湾对东盟贸易投资的发展历史。最后详细 研究了台湾地区的南向政策以及新南向政策的相关历史背景。

第三章为研究方法。这一章主要介绍了本文使用的计量模型方法以及数据来源，同时框定了台湾两次南向政策所使用的数据范围。

第四章为实证结果。这一张主要解读回归结果，以及结果背后所蕴含的信息，通过分析结论进一步呼应本文主题。

第五章为结论与建议。无论李登辉当局提出的南向政策或是蔡英文当局提出的新南向政策，本质都是违背自然经济规律，使用政治手段干涉经济，既不符合客观经济规律又不符合台湾长远的利益。面对台湾当局这一系列政策的影响，大陆应该谨慎应对，未雨绸缪，防范系统性危机的同时积极维护两岸关系。

### 论文创新与不足点

本文创新点在于，对于台湾南向而言，目前已有文献虽然对不同时期南向政策的实施效果进行了探究，但大多数均仅使用描述性统计对政策的相关贸易数据进行展示和文献分析，缺乏对数据的深入挖掘及数理模型的使用。[@段哲哲2020蔡英文当局]利用双重差分法（difference in differences, DID）以及倾向得分匹配（propensity score matching）对新南向政策的出口数据进行了研究，但其研究仅使用台湾出口数据，未使用台湾进口和投资的相关数据，研究范围没有涉及李登辉政府的南向政策时期，且结论缺乏使用基于事件研究法（event study method）的平行趋势检验作为支撑。在这种背景之下，我们希望从台湾地区进出口以及投资的数据出发，通过计量模型探究两次南向政策是否有效。因此，研究台湾地区的历次南向政策，对探究台湾经济发展规律具有很强的现实指导意义。

本文的不足点，其一在于没有利用到台湾全部的投资数据。对于投资而言，在台湾投资全面自由开放之前，应当承认间接投资在台湾对外投资占有极其重要的份额，但是这部分数据搜集颇为艰难，且数据的搜集做出具有一致性的质量的保证，故本文采用了对外直接投资(FDI)作为投资的衡量指标。其二在于没有对已有通用计量方法进行创新。目前，对于双重差分法而言，近年来国际前沿研究对于方法本身做出了一些改进和修正，例如[@goodman2021difference]、[@callaway2021difference]和[@sun2021estimating]的研究均对近年来双重差分法平行趋势检验的使用进行了深入的剖析和反思，而对于这部分内容目前尚未有国际统一的标准，故本文使用的平行趋势检验仍为事件研究法与双向固定效应结合的方案。


## 文献综述

### 南向政策

**1.关于南向政策产生的原因**

[@王和英1995台湾当局推行]提出台湾当局推行南向政策在于两岸经贸合作的迅速发展逐步削弱了台湾经济上的优势地位，并使台湾对大陆市场产生了过分依赖。台湾当局意图把台商从大陆引向东南亚，其目的是握住与大陆抗衡的筹码，也是台当局针对香港即将回归祖国而采取的一项因应措施。[@冯邦彦2003台湾当局]分析了台湾地区南向政策的起源、演变与未来发展趋势，认为台湾当局再三推行南向政策，有政治，经济等方面的考虑。经济方面，为了阻止台商的西进的潮流，台湾当局希望能与东南亚国家增进经贸关系，以东南亚国家地区为台湾经贸腹地，尽早入驻东盟地区。政治方面，在东南亚经济危机后，台湾提出援助东南亚国家的计划，企图不"建交"而相互承认。[@王勤2003台湾在东南亚直接投资的现状与趋势]认为台湾当局试图通过南向政策把资产重点转移到东南亚，从而降低两岸经贸的依赖程度和产业转移的政治风险。[@刘青建2008对台湾]的研究指出，南向政策的实施主要有三个目的，一是分散台商对大陆投资，二是推进台湾同东南亚国家的务实关系，三是配合"台独"，为"台独"奠定外交基础。

**2.关于南向政策的实施效果**

[@刘青建2008对台湾]指出，从1993年11月至1996年，南向政策的实施使台商在东南亚国家的投资逐年增加，并一定程度抑制了台湾资本对中国大陆的投资。但1998年，由于东南亚各国受到金融危机的冲击，经济衰退，市场疲软，再加上部分东南亚国家政局不稳和排华等因素，南向政策并未取得有效的成果。[@李航飞2018经贸视角下中国台湾]利用2001-2015年的台湾地区贸易数据，通过社会网络分析 (SNA) 方法和VAR脉冲响应函数探究了中国大陆在贸易网络中的地位以及其对台湾地区的影响，结果表明，新南向国家对中国大陆经济的依赖程度，远高于其对中国台湾经济的依赖程度，中国大陆在台湾地区贸易网格格局中处于核心地位，中国大陆对于提升台湾地区贸易网络地位至关重要，中国大陆与台湾的对外贸易对台湾经济的促进程度远高于新南向国家对台湾经济的促进程度。

### 新南向政策

**1.关于新南向政策产生的原因**

[@盛九元2016蔡英文的]指出，相比“南向政策”，“新南向政策”的核心仍是意图进一步加强台湾与东盟国家之间的经贸关系，强化台湾位于东盟国家的竞争优势，减轻台湾经济对大陆的依赖与资金的“磁吸效应”，进而解决台湾的“安全”问题。[@陈先才2020蔡英文当局]的分析表明，在经济方面，台湾当局将提升经济的希望转移至东南亚新兴市场，用“南向”对抗“西进”，以提升岛内经济为导向，加强与相关国家经贸关系合作，转移岛内过剩的产能，以此降低对大陆的经济依赖，实现经济上"脱中"。在意识形态方面，蔡英文当局利用岛内民众的期望，通过构建与新南向国家利益整合的蓝图，弱化台湾地区对大陆市场的好感，用经济上的“渐进式”脱中，达到“脱中”的最终目的。国际形势方面，蔡英文将印太地区列入新南向政策的扩展名单，借助大国间政治博弈，推行“亲美卖台”战略，响应美国抑制中国的发展布局，"反中抗中"意图十分明显。

**2.关于新南向政策的实施效果**

[@2019Taiwan]分析了南向政策的历史沿袭以及台湾海峡的国际形势，指出新南向政策的实施促进了"台美关系"，并且“以人为本”的新南向政策的实施释放出台湾当局的温和“外交信号”。[@段哲哲2020蔡英文当局]基于2008-2018年台湾对外出口贸易数据，使用PSM-DID（倾向得分匹配与双重差分法）计量方法实证检验表明，蔡英文当局"新南向政策"对台湾地区出口贸易没有作用，"新南向"国家出口增长动力来自于相关国家内部经济增长与内需市场的扩大，台湾当局试图摆脱中国大陆经济依赖而寄希望于“新南向政策”并不理智。[@2021新南向政策背景下越南學生來臺留學動機之探討]指出，蔡英文政府提出的新南向政策中，教育政策方面特别重视建设台湾与东盟以及东南亚国家的学术交流和人才吸引。2017年台裔学生在新南向各国留学总人数增加近20%。
