# 背景研究

台湾地区的现代经济，是以日本殖民统治时期的农业和轻工业为基础发展起来的。日清《马关条约》签订之后，台湾被割让给日本，台湾的出口重心由中国转向了日本，被纳入了日本经济体系和帝国经济圈中。日据时期，台湾对日贸易与转口贸易逐渐盛行[@林玉茹]。日治时期台湾财政依赖日本国库的补助。此阶段台湾的经济是典型的殖民地经济模式，即以宗主国的需求为中心整体规划。台湾经济的发展方略为“工业日本，农业台湾”，而在1930年以后，因日本对外战争需要，台湾的经济重心转为工业化[@涂照彦1975日本帝国主義下の台湾]。日治时期，台湾的糖业、农业、金融等行业实现了一定的发展，水利、水电、交通、海港、运河和铁路建设都进行了不同程度的建设，为台湾经济打下了一定的发展基础。但日据时期晚期，台湾总督府为了支撑日本对外的侵略战争，在台湾实施了严格的贸易管制政策，加强统制贸易[@白纯2005光复初期台湾的贸易管制政策]。如图1^[数据来源：善后救济总署台湾分署经济扶正室《台湾省主要经济统计》，1946年9版，第65页。]所示，从1941年到1945年台湾对日本的进出口均高于对其他国家的进出口总和。

```{r, echo=FALSE, fig.cap='1941-1945台湾对外贸易统计'}
tw1945 <- read_csv('data/1945taiwan.csv', show_col_types = FALSE)

ggplot() +
  geom_point(data = tw1945, aes(x = Year, y = 数值, color = 类型, shape = 类型)) +
  geom_line(data = tw1945, aes(x = Year, y = 数值, color = 类型, linetype = 类型)) +
  scale_color_manual(values=c("blue", "blue","red", "red")) +
  scale_linetype_manual(values=c(1, 2, 1, 2)) +
  xlab("年份") + 
  ylab("统计值（单位：台币千元）")
```

1945年台湾光复，联军总部宣布战后日本不能立即对外通商，使台湾失去对年来最大贸易对象，加之国民政府台湾调查委员会对战后台湾的总方针是：“恢复台湾、内地及输出入口贸易。对于输出入，应加管制，并计划增加土产销路”，使台湾对外贸易受到很大影响。国民政府成立了行政长官公署和物资调节委员会对全岛进行贸易管制，通过管制进出口，将贸易业务完全由贸易局垄断经营。这些贸易管制政策在战后物资匮乏的背景下，在稳定物价和调节民生方面起到了一定的积极作用，但这种贸易管制也遭到了台湾民众尤其商人阶级的反对。在国民政府的贸易管制下，1946、1947、1948年台湾省对内地省份进出口总额分别占台湾总进出口额的94%、91%和86%[@白纯2005光复初期台湾的贸易管制政策]。作为垄断者的政府拥有追求利润极大化的能力，所以这段时间的贸易管制称为台湾省政府的重要财源。


