\newpage

# 摘要

**摘要**

台湾作为典型的岛屿，全岛约七成面积是山地和丘陵，漫长的中央山脉横断东西，在很长的一段时间内交通不便，必要的生产资料与产出品难以自给自足，于是对外贸易就成为台湾经济发展的命脉。自从第二次世界大战结束台湾光复开始，台湾经济经历了几十年的快速增长，缔造出“台湾奇迹”，成为“亚洲四小龙”的成员。从对外出口的内容上看，台湾拥有丰富的尖端制造业，在半导体、通信、电子精密制造等方面具有突出领先的地位，主要通过高科技产业出口赚取外汇。从对外出口的方向上看，伴随着台湾经济结构从劳动密集型向资本密集型和人力技术密集型的转变，台湾的进出口重心经历了从美国与日本向中国大陆和东盟国家的转移。此时，随着中国大陆改革开放之后对台湾展现出强大的“群聚效应”，令台湾当局忧心忡忡，祭出试图引导台商将对中国大陆的进出口及投资份额向东南亚及大洋洲国家转移的“南向政策”与“新南向政策”，意图在一定程度上影响台湾进出口及投资的既有格局，并扩张台湾在东南亚地区的“政治影响力”。这种试图使用政治手段干涉经济的行为不仅与客观经济规律相背离，也无益于陆台人民的友好交流与两岸关系的健康发展。

基于这种现状，我们利用1990-2019年台湾进出口贸易与对外直接投资的相关数据，运用双重差分法对台湾地区两次南向政策的实施效果进行了实证研究。结果表明：从总体上看，李登辉当局提出的南向政策与蔡英文当局提出的新南向政策对台湾进出口及对外直接投资的比重分布没有作用，并且政策的实施对于台湾进出口及对外直接投资的比重亦没有持续正向的滞后效应。尽管南向经济为台湾提供了新的经济发展思路，但试图脱离中国大陆的经济辐射对台湾经济的长久健康发展没有好处。台湾当局应审时度势，加强与祖国大陆的经济文化交流，这既是推动两岸经贸关系和谐发展的必要前提，又是维持两岸中国人友好发展的关键手段。

**关键词**

南向政策；双重差分法; 事件研究法；台湾经济

\newpage

**Abstract**

As a typical island, 70% area of Taiwan is mountainous and hilly. The long central mountain range cuts across the east and west. For a long time, Taiwan's transportation is inconvenient, and the necessary means of products and production are difficult to be self-sufficient. Therefore, foreign trade has become the lifeblood of Taiwan's economic development. Since the Taiwan's recovery day at the end of World War II, Taiwan's economy has experienced decades of rapid growth, created a "Taiwan miracle", and became a member of the "Four Asian Tigers". From the perspective of export content, Taiwan has a sophisticated and cutting-edge manufacturing industry, with a prominent leading position in semiconductor, communication, electronic precision manufacturing, and other fields, mainly earning foreign exchange through high-tech industry exports. From the perspective of export direction, with the transformation of Taiwan's economic structure from labor intensive structure to capital intensive structure and human technology intensive structure, Taiwan's import and export focus has experienced a shift from the United States and Japan to Chinese Mainland and ASEAN countries. At this time, Chinese Mainland has shown a strong "cluster effect" on Taiwan after its reform and opening-up, which worried the Taiwan authorities. Taiwan authorities set "southward policy" and "new southbound policy" and tried to guide Taiwanese businessmen to transfer the import, export and investment shares on Chinese Mainland to Southeast Asian and Oceanian countries, with the intention of influencing the existing pattern of Taiwan's import, export and investment  and expanding Taiwan's "political influence" in Southeast Asia. This attempt to use political force to interfere in the economy not only deviates from objective economic laws, but also is not conducive to friendly exchanges between mainland and Taiwan people and the healthy development of cross-strait relations.

Based on this situation, we used data of Taiwan's import and export trade and foreign direct investment from 1990 to 2019 to process an empirically study about the implementation effect of twice policies in Taiwan using the difference in differences method. The results indicated that the southward policy proposed by the Lee Teng hui authorities and the new southbound policy proposed by the Tsai Ing wen authorities have no effect on the proportion distribution of Taiwan's imports, exports, and foreign direct investment in total. Moreover, the implementation of the  policy and the new southbound policy has no long-term positive lag effect on the proportion of Taiwan's imports, exports, and foreign direct investment. Although the southward economy has provided some new ideas for Taiwan's economic development, trying to break away from Chinese Mainland's economy influence on Taiwan's economy is not beneficial for Taiwan's economy. The Taiwan authorities should assess the situation and strengthen economic and cultural exchanges with the mainland of China. This is not only a necessary prerequisite for promote the harmonious development of cross-strait economic and trade relations, but also a key means to maintain the friendly development of the Chinese people on both sides of the Taiwan Strait.

**Key Words**

"Go South Policy", difference in differences, event study method, Taiwan's economic
