# 绪论

## 研究背景及意义

1987年，台湾地区前“行政院长”孙运璿接受了《天下杂志》的专访。他坦言，对于近年来台湾对大陆探亲政策的开放，工商业界也希望政府能逐渐开放前往大陆投资的渠道，使转口贸易增加。他就通商与投资方面，表达了自己的看法，认为台湾须谨慎应对大陆的通商与通航需求，避免在经济上过度依赖大陆市场[@孫運璿]。

此时，对于台湾贸易与投资的未来发展方向，岛内逐渐形成了“西进”与“南向”两个派别[@吳重禮1999戒急用忍]。西进派主张拥抱大陆改革开放的新趋势，将台湾未来经济发展的重心向中国大陆靠拢，借此促进台湾经济的发展。南向派则希望利用东南亚国家巨大的潜在需求，加强台湾对东南亚国家的贸易与投资，借助东南亚国家的贸易替代效应，避免台湾经济过分依赖某一单一巨型经济体[@刘荣茂2005南向政策]。

随着台湾当局逐渐开放两岸贸易和投资限制，台商之间形成西进大陆的“磁吸效应”，创造出台商群体间的“西进潮流”。针对日益密切的两岸经贸关系，台湾当局担心两岸经贸依存度的提升将产生有关自身“安全保障”方面的危险[@舒萍1999台湾当局的]。为了应对西进潮流，当局推出名为“根留台湾”的政策及相应措施，希望以台湾为中心，将产业垂直分工中高附加值的研发、设计等部门留在台湾，将低附加值的加工、装配等部门转移岛外，试图通过塑造根留台湾的垂直分工体系，放缓台商西进大陆的速度[@刘荣茂2005南向政策]。

1988年，蒋经国于其任内意外病逝，根据台湾地区相关法律，李登辉继任。李登辉任期中，政治上结束了两蒋时期的“动员戡乱”条款，加速宪政化，并力图实现“台湾政权台湾化”。经济上则谋划推行基于台湾本土的收缩性经贸政策，试图使经济服从于政治，将对大陆的经济政策与政治政策统一起来。1996年，李登辉在“全国经营者大会”提出“戒急用忍^[“戒急用忍”原为满清康熙帝赐予皇子胤禛的座右铭。]”的经济方针，劝阻台商“步子不要太快，必要时应多踩刹车”，避开大陆经济锋芒才能“行稳致远”[@舒萍1999台湾当局的]。

“戒急用忍”方针覆盖了李登辉执政的整个时期，并实质地成为了台湾当局推行“南向政策”的指导思想。1993年，台湾当局为分散台湾岛内各厂商海外投资的地区分布，并激发东南亚地区的经贸投资发展潜力，同时为解决“区域边缘化之疑虑”、“台湾运营风险”以及“台商函盼政府伸出援手”等问题，开始设计以东南亚与大洋洲国家为主要经贸拓展对象的贸易投资方案。当年台湾“经济部”即设立“南向专案小组”，并成立“亚洲台湾商会联合总会”，再由李登辉提出“南进政策说帖”。1993年年底，当局通过了“加强对东南亚地区经贸工作纲领”，正式启动了南向政策。南向政策即是一系列政治、外交及经济政策的统称，其意图在于推进台商的海外投资方向向东南亚地区转移，并使用经济力量扩张一定的政治影响力，减少对大陆的经济依赖[@刘青建2008对台湾]。此后，此阶段南向政策经过前后两次延长，至2002年年底为止。

南向政策后期，恰逢东南亚金融危机，台商在东南亚地区的产业遭受重创，于是台湾经济产业界要求经济发展松绑“戒急用忍”指导思想的声音与日俱增。陈水扁于2000年宣布要将“戒急用忍”的政策逐步替换为“积极开放，有效管理”的新路线[@bing2017taiwan]。尽管如此，陈水扁政府为适应台湾加入世贸组织以及东盟自贸区成立的经济形势改变，还是重启了南向政策，但收效甚微，政府及媒体对此也甚少提及，到马英九执政时期已名存实亡，政治意涵大幅减少[@黄奎博]。

2015年，时任民进党主席的蔡英文宣布民进党在未来执政后将推动“新南向政策”。在此前的台湾地区领导人选举中，新南向政策是民进党阵营的一项重要政见。蔡英文表示过去李登辉政府推行的南向政策旨在引导台湾企业在东南亚地区的投资，基于该政策，未来民进党政府将进行持续推进。新南向政策的核心，仍是进一步强化与东盟国家关系、降低对中国大陆的经济依赖、减少大陆对台湾人才及资源的磁吸效应和保证台湾的“安全”[@盛九元2016蔡英文的]。对此政策，蔡英文当局制定了“四大主轴”、“五大旗舰计划”、“三大潜力领域”。通过与“新南向”国家建立多个维度的合作关系，将经贸合作方面的利益转化为“外交利基”[@李鸿阶2019台湾当局]。

台湾既存在着自然资源缺乏、交通不便与自身消费市场本身较小等“先天性难题”，也存在岛内经济发展强依赖外贸经济和区域经济边缘化等“后天性难题”，凭借自身自给自足难以实现持续的经济增长。对台湾而言，外贸与经济增长密切相关，对外出口则相关程度最高，是重要的经济命脉[@李非2009台湾经济发展规律探析]。从二十世纪五十年代开始，美国和日本是台湾地区前两大贸易伙伴。但从二十一世纪开始，中国大陆与东盟国家经济相继崛起，使台湾的贸易重心逐渐转移到了东南亚地区和中国大陆。2008年，随着台湾地区第二次政党轮替，国民党重新执政，台湾与大陆签订了《海峡两岸经济合作框架协议》，进一步增进了海峡两岸的“三通^[指通商、通航、通邮。]”，促进了两岸的贸易与投资。如今，大陆已经成为台湾的最大贸易伙伴，至2018年台湾对大陆出口值已逾900亿美元，年增速接近10%。自李登辉政府至蔡英文政府，南向政策多次被台湾当局提出，并搭配相应的配套政策，其设置的目的都有关经济与政治两个维度，而且进行了实质性的预算支援。但在台湾经济经历“亚洲四小龙”奇迹之后，就再难见到彼时的蓬勃发展。随着中国大陆经济实力与日俱增，海峡两岸经贸关系稳步提升，区域经济一体化的潮流不可阻挡，这不禁让我们疑问：以远离大陆政治导向驱动的南向经济，是否有利于台湾的经济发展？南向，是否是有利台湾经济的正确发展方向？

## 研究思路和研究方法

### 研究思路

**文献综述法**

本文基于已有有关台湾新旧南向政策的文献进行研究，参考范围包含中英文的相关论文、杂志期刊、报纸新闻、书籍、专业的研究报告等。本文同时从近代台湾贸易的发展史出发，通过文献对台湾东盟贸易以及南向政策及新南向诞生与发展的相关资料进行整理与提炼，从中找出相关的要点，参考文献信息列出论文撰写的大纲提要，最终得出有价值的观点。

**比较分析法**

在新南向政策实施之前，台湾当局已经推行了数波南向政策，南向政策与新南向政策的诞生与实施既有背景上相同点，又有许多不同点。在论文的撰写中我们比较了数次南向政策的异同，同时深入探究了南向政策与新南向政策的区别与联系。

**历史分析法**

本文从台湾近代贸易的发展历史出发，详细描述了从日本殖民统治到国民政府迁台，再到两岸经济深入交流以来台湾对外经贸投资的发展过程，以及台湾贸易产业结构如何从进口替代型转变为出口扩张型。最后，本文也对台湾南向政策以及新南向政策的历史背景做了详细的分析。

**数据分析法**

本文在撰写中使用了表格、图形和公式等方式对统计量和统计模型进行描述，其中涉及时间序列图形、热力地图、函数图像、数学模型等诸多种表达类型，最后使用了计量统计模型对论点进行论证，保证了论文结论的科学性。

### 分析框架

本文共分为五个章节。

第一章为绪论。这一章主要介绍了南向政策与新南向政策相关的历史背景与本研究的意义所在，同时对概念界定、研究思路与方法、文章框架做了阐述，最后总结了论文创新点与不足之处。

第二章为文献综述，这一章分类将学界现有有关台湾南向政策和新南向政策的相关文献进行概述，整理了研究状况并总结了相关结论。

第三章为背景研究。这一章主要梳理了台湾对外贸易发展的历史路径，从二战结束台湾光复形成的贸易格局出发，到冷战期间台湾对外出口贸易发展的路径变化，以及台湾对东盟贸易投资的发展史，最终通过上述研究的铺垫，分析了南向政策以及新南向政策的相关历史背景。

第四章为研究方法。这一章主要介绍了本文使用的计量模型以及数据来源，同时指定了两次南向政策研究中所使用的数据范围以及选取依据，并对数据进行了较为详尽的描述性统计。

第五章为实证结果。这一张主要解读计量回归的结果，通过分析回归结果解读南向政策与新南向政策的实际效用以及相关控制变量背后所蕴含的额外信息。

第六章为结论与建议。无论李登辉当局提出的南向政策或是蔡英文当局提出的新南向政策，本质都是违背自然经济规律，使用政治手段干涉经济，既不符合客观经济规律又不符合台湾长远的利益。面对台湾当局这一系列政策的影响，大陆应该谨慎应对，未雨绸缪，防范系统性危机的同时积极维护两岸关系。

### 概念界定

投资指依赖一定数量的资本，为了一定的目的，往一定的地区和一定的经营项目进行投入，表现为厂商为购买新的资本物而进行的支出。投资品从资本输出地流到输入地，通常有两种形式：一种是直接投资，一种是间接投资。直接投资指投资者将资本物直接运输到投资地，而间接投资指投资者通过第三方转运的形式将资本物运输到投资地。历史上，台湾地区对海外投资的种类既有直接投资，也有间接投资。尤其由于台湾投审会对向中国大陆的投资申请具有管制措施，台商选择英属维尔京群岛等地区进行资本第三国转运进而对中国大陆进行投资的情况较为多见。由于数据完整性的原因，本研究主要的研究对象是直接投资而非间接投资。

## 论文创新与不足点

### 论文创新点

本文创新点在于，虽然目前已有文献对不同时期南向政策与新南向政策的实施效果进行了探究，但大多数仅使用描述性统计的方式对政策涉及的相关贸易数据进行展示，缺乏对数理模型的构建以及对数据的深入挖掘。尽管已有文献[@段哲哲2020蔡英文当局]利用双重差分法（difference in differences, DID）以及倾向得分匹配（propensity score matching）对新南向政策的出口数据进行了研究，但其研究仅使用台湾出口数据，未使用台湾进口和直接投资的相关数据，研究也没有涉及李登辉政府提出的南向政策，且结论缺乏使用基于事件研究法（event study method）的平行趋势检验作为支撑。基于上述考虑，我们希望从台湾地区进出口以及对外直接投资的数据出发，通过计量模型分别探究两次南向政策是否有效。因此，本文基于台湾进出口及投资的贸易数据，对南向政策及后续新南向政策均进行了计量统计模型的构建与检验，并且使用基于事件研究法的平行趋势检验对回归结果进行了检验，加强了结论的科学性，可以对现有台湾地区南向经济研究的空白领域进行补充。本研究对探究台湾地区历次南向政策和新南向政策的实施细节，以及寻找台湾外向型经济发展规律具有一定的作用。

### 论文不足点

本文的不足点，其一在于没有利用到台湾间接投资数据。对于投资而言，应当承认间接投资在台湾对外投资占有一定的份额，但是这部分数据搜集较为困难，且无法对相应数据的统计保持一致性的规范，故本文采用了对外直接投资（FDI）作为投资的衡量指标。其二在于没有对已有通用计量方法进行创新。目前，对于双重差分法，近年来国际前沿研究对于方法本身的假定做出了一定的探索，也对平行趋势检验的使用进行了深入的剖析和研究，并提出了相应的理论与技术改进，如提出了对DID效应 的分组分解[@goodman2021difference]，理论推导出在更宽松的假设下更加稳健的DID估计量[@callaway2021difference]，以及对基于双向固定效应的平行趋势假定检验的深入探讨[@sun2021estimating]。对于这部分内容，本文仍使用较为严格假定下的DID估计量和事件研究法与双向固定效应结合的平行趋势假定检验进行分析。
