# 文献综述

目前关于台湾地区南向政策与新南向政策相关的文献主要分为两类，一类是通过对新闻报道、政府公布数据的相关内容进行描述性分析，另一类是通过使用较为复杂的数理模型对数据进行深入发掘。从文献涉及方向上，可以分为台湾与东盟的贸易相关，台湾南向政策相关，台湾新南向政策相关。

## 关于台湾地区与东盟贸易

周明伟(2003)的研究表明，21世纪初期台湾与东盟的贸易呈现出两大特点。其一，东盟在台湾贸易中所处的角色日益重要，从90年代初期台湾与东盟贸易占台湾对外贸易总比重不到10%增长到2001年和2002年已达13.5%和13.4%。1993-2003年台湾地区与东盟贸易额增速几乎每年都达到两位数，远高于与美国、日本或欧洲的增长率。其二，在东南亚金融危机发生前后，台商对东盟投资与出口剧减，导致台湾与东盟贸易平衡发生转变，贸易呈现出从顺差转为逆差的态势[@DDYT200310005]。

王敏(2011)梳理了自二十世纪五十年代起台湾与东盟国家在不同时期的经贸特点，提出四点台湾与东盟的经贸发展特征。其一，台湾与东盟各国间的经贸关系呈现出差异性与外向性，双方贸易大多属于加工贸易，以欧美市场为导向，双方贸易额常常受到宏观经济的影响。其二，东盟在台湾贸易体系中的地位日益提升，而台湾却在东盟贸易体系中的地位相对下降。台湾面临东盟内部经济一体化的进程推进、区域贸易的增长以及东盟与中国大陆、日本、韩国等国家或地区签订自贸协议等威胁，难以坚挺其在东盟外贸体系中的地位。其三，台湾与东盟的经贸关系与两岸经贸关系具有一定竞争性，尤其台湾与东盟对台湾与中国大陆之间的投资具有一定的替代效应。其四，台湾与东盟发展经贸关系的最终目的，仍是希望发展两者的“实质关系”，拓展台湾地区的“国际空间”[@TWYJ201104012]。

HOAN, et al. (2019)指出，尽管台湾与东盟国家具有互补的贸易结构，但其与日本、韩国、中国大陆等地区对东盟的贸易结构相比仍然显示出高度的专业化，故贸易结构多样化程度较低。台湾与东盟在高科技制造业，特别是电子和电子零件制造领域具有较高的贸易比重。然而，台湾与东盟的经贸关系取决于台湾与中国大陆之间稳定的两岸关系，东盟不希望台湾与东盟之间关系的发展速度超过台湾与中国大陆之间的两岸关系发展速度。因此，东盟和其他国家或地区将坚持维护稳定的台海关系，以长期稳定增加台湾与东盟之间的贸易往来[@hoan2019taiwan]。

## 关于南向政策

### 关于南向政策产生的原因

王和英(1995)指出，台湾当局推行南向政策的原因有三点。其一在于两岸经贸合作的迅速发展逐步削弱了台湾经济上的优势地位，并使台湾对大陆市场产生了过分依赖。台湾当局意图把台商从大陆引向东南亚，其目的是握住与大陆抗衡的筹码，也是台湾当局针对香港即将回归祖国而采取的一项因应措施。其二在于台湾当局希望通过南向政策进一步增强与东南亚国家的经贸关系，以此扩大海外市场。其三在于台湾当局希望通过经贸关系的提升来促进与东南亚国家的实质性关系[@王和英1995台湾当局推行]。

冯邦彦等(2003)分析了台湾南向政策的起源、演变与未来发展趋势，认为台湾当局再三推行南向政策，有政治，经济等方面的考虑。经济方面，为了阻止台商西进的潮流，台湾当局希望能与东南亚国家增进经贸关系，以东南亚地区为台湾经贸腹地，尽早入驻东盟地区。政治方面，在东南亚经济危机后，台湾提出援助东南亚国家的计划，企图不“建交”而相互承认。台湾当局推行南向政策，本质上是希望使用政治影响经济，这是台湾当局坚持“台独”，对两岸经济健康发展充满警惕的标志[@冯邦彦2003台湾当局]。

王勤(2003)总结了1987-1991年间东南亚各国的官方统计数据，台湾在东南亚六国直接投资达83.71亿美元，年均16.74亿美元，双边贸易额从51.67亿美元增长至127.8亿美元，增长1.5倍，而到了1992-1993年，台湾对东南亚国家的投资骤然下降，这两年台湾在东南亚六国累积投资25.83亿美元，年均12.92亿美元。在这种背景之下，台湾当局试图通过南向政策把资产重点转移到东南亚，从而降低两岸经贸的依赖程度和产业转移的政治风险[@王勤2003台湾在东南亚直接投资的现状与趋势]。

刘青建(2008)的研究指出，南向政策的实施主要有三个目的，一是分散台商对大陆投资，减轻台湾对大陆经济的依赖；二是推进台湾同东南亚国家的务实关系，打开双方务实外交的瓶颈，增加双方高级官员的互访与机构的互设；三是配合“台独”，为“台独”奠定外交基础[@刘青建2008对台湾]。

### 关于南向政策的实施效果

王勤(2003)的研究表明，从1997年开始，东南亚部分国家积极进行产业结构升级，增加对技术密集型产业的投资，导致当地用工成本上升，造成台商投资明显下降，在马来西亚有43家台企因亏损而关闭，而原本由台湾当局推动建立的4个工业区只保留了位于越南和菲律宾的两个。1997年爆发的东南亚金融危机恶化了东南亚地区的投资环境，对于有东南亚相关业务贸易往来的台商中有84.4%面临经营困难，而对东南亚直接投资的厂商中有76%受到冲击。这时期台湾对东南亚的投资额急剧下降，1997-2000年年均投资为23.85亿美元[@王勤2003台湾在东南亚直接投资的现状与趋势]。

刘青建(2008)指出，从1993年11月至1996年，南向政策的实施使台商在东南亚国家的投资逐年增加，并一定程度抑制了台湾资本对中国大陆的投资。但后来由于东南亚各国受到金融危机的冲击，经济衰退，市场疲软，信贷困难，再加上部分东南亚国家政局不稳和排华等因素，南向政策在经济上并未取得有效的成果。同时，南向政策的发展并没有分散台商对大陆的投资。在东南亚经融危机后，台商纷纷转投大陆。从推进与东南亚国家的务实关系方面，通过南向政策的实施，台湾与除缅甸、老挝和柬埔寨外的东南亚七国都互设了代表机构，并将其功能从经贸业务扩展到领事事务，并将代表机构更名，突出“台北”以显示其“独立政治实体”的国际地位。台湾当局也与新加坡、马来西亚、泰国、越南和印尼等国签订了投资保证协定，与新加坡、马来西亚、泰国和印尼签订了避免双重征税协定，与菲律宾签订了渔业协定和科技合作协定，并与新加坡签订了暂时通关协定[@刘青建2008对台湾]。

## 关于新南向政策

### 关于新南向政策产生的原因

Yang, et al. (2016)的研究认为，从历史上看，台湾地区参与东南亚国家事务的程度主要依赖于地区领导人之间的私人关系，随着东南亚国家的寡头政治逐渐衰落，台湾与东南亚国家的经贸合作应当以更加新颖的方式进行。新南向政策并非从“西进”中国大陆和“南向”东南亚地区二选一，而是两者并行设置的一种主动出击式的经济战略。台湾地区的新南向政策为东南亚地区的经济发展可以提供更强的动力[@yang2016contextualizing]。

盛九元(2016)指出，近几年来两岸经济的加速交流造成台湾对大陆的“过度倾斜”。相比南向政策，新南向政策的核心仍是希望进一步加强台湾与东盟国家之间的经贸关系，强化台湾位于东盟国家的竞争优势，借助台湾在资本和技术方面的优势，维持其相关产业在东盟国家的竞争力，应对所谓“红色供应链”，同时减轻台湾经济对大陆的依赖与大陆对台湾资金的“磁吸效应”，进而解决台湾的“安全”问题[@盛九元2016蔡英文的]。

刘相平(2016)认为，新南向政策只是南向政策的“翻版”，台湾的经济要素禀赋决定了台湾必须走对外高度依赖的开放型发展模式。新南向政策企图在全球一体化的背景下促进台湾与东南亚及印度经济关系，这尽管具有一定的合理性，但在大陆积极拓展东南亚与印度经济合作，推行“一带一路”以及RCEP（区域全面经济伙伴关系）的背景下，执行新南向政策对分解台湾对大陆贸易依存度的风险非常明显，对两岸经济融合十分不利[@LAGX201604016]。

单玉丽(2016)指出，新南向政策的实施展现出三大特点。其一，从空间上看，南向政策实施的对象主要是东南亚国家，而新南向政策加入了包括印度的众多南亚国家；其二，从内容上看，南向政策包括台湾企业在东南亚的贸易与投资，而新南向政策还试图在文化、教育和人才等方面进行探索；其三，从目的上看，新南向政策的实施体现了台湾当局在弱化与大陆经贸关系方面的强烈意图，不仅是对台湾经济的多元化与国际化的全盘构思，也是确保“台湾政治上自主性”的重要考量[@TWYJ201605002]。

张宜鑫等(2017)指出，在中国大陆经济发展减速和劳动力价格优势逐渐丧失的背景下，随着东盟经济共同体的建立南亚大国印度的崛起，台湾当局推动新南向政策意在利用东盟和印度资源、市场和人口方面的巨大优势，扩展台湾内需，突破出口衰竭困境。同时，随着南海争端日益激化，美国极力组织日本、印度及东盟国家与中国大陆进行对抗，而新南向政策与美国“亚太再平衡”战略一脉相承，深得美日认同。蔡英文当局以经济为名，真正目的在于通过与东盟及南亚建立良好的经贸关系，将经济关系转化为“外交关系”[@XDTW201702006]。

陈先才等(2020)的分析表明，在经济方面，台湾当局将提升经济的希望转移至东南亚新兴市场，用“南向”对抗“西进”，以提升岛内经济为导向，加强与相关国家经贸关系的合作，转移岛内过剩的产能，以此降低对大陆的经济依赖，实现经济上"脱中"。在意识形态方面，蔡英文当局利用岛内民众的期望，通过构建与新南向国家利益整合的蓝图，弱化台湾对大陆市场的好感，用经济上的“渐进式”脱中，达到“脱中”的最终目的。国际形势方面，蔡英文将印太地区列入新南向政策的扩展名单，借助大国间政治博弈，推行“亲美卖台”战略，响应美国抑制中国的发展布局，“反中抗中”意图十分明显[@陈先才2020蔡英文当局]。

### 关于新南向政策的实施效果

熊俊莉(2018)总结，2017年台湾经济总体呈现出弱增长趋势，进出口对台湾经济增长贡献较大，但内需对经济增长贡献仍不足。在台湾内部，除了半导体等传统优势产业，台湾经济缺乏新的亮点产业，大陆作为台湾最大的贸易和投资伙伴，是拉动台湾经济复苏的重要因素。展望2018年，台湾经济无法摆脱“弱复苏”的境地[@XDTW201801004]。

李航飞等(2018)利用2001-2015年的台湾地区贸易数据，通过社会网络分析 (SNA) 方法和VAR脉冲响应函数探究了中国大陆在贸易网络中的地位以及其对台湾地区的影响，结果表明，新南向国家对中国大陆经济的依赖程度，远高于其对台湾地区经济的依赖程度。中国大陆在台湾贸易网格格局中处于核心地位，对于提升台湾地区贸易网络地位至关重要。同时，就对台贸易对台湾经济的促进程度而言，中国大陆远高于新南向国家[@李航飞2018经贸视角下中国台湾]。

Chen(2019)分析了南向政策的历史沿袭以及台湾海峡的国际形势，指出新南向政策的实施对维持“台美关系”非常重要，有助于将台湾外交政策与美国外交政策联系起来，也有利于台湾当局向美国献上“投名状”，安抚美国情绪。以“以人为本”为出发点的新南向政策也有助于台湾当局对东南亚国家释放出温和的交流信号[@2019Taiwan]。

段哲哲等(2020)基于2008-2018年台湾对外出口贸易数据，使用PSM-DID（倾向得分匹配与双重差分法）计量方法进行实证检验表明，蔡英文当局新南向政策对台湾地区出口贸易没有作用，新南向国家出口增长动力来自于相关国家内部经济增长与内需市场的扩大。从战略角度，新南向政策对促进台湾地区与相关国家的贸易关系有一定意义，而台湾当局寄希望于新南向政策摆脱中国大陆经济依赖的行为并不理智[@段哲哲2020蔡英文当局]。

Hung(2021)指出，蔡英文政府提出的新南向政策中，开放了留学与教育政策，尤其重视建设台湾与东盟以及东南亚国家的学术交流和人才吸引，以学习语言、体验文化、进修课程或实习等理由选择来台的人才逐年升高。同时，台生在东南亚地区的留学热情也有所上升，2017年台裔学生在新南向各国留学总人数增加近20%[@2021新南向政策背景下越南學生來臺留學動機之探討]。

## 文献评述

通过对文献进行梳理和分析后可以得出，现有文献主要的工作内容是对南向政策与新南向政策实施的起因、经过和结果进行描述性分析和统计。其一，文献中多次提到了南向政策与新南向政策被提出所包含的初始动机，如避免对中国大陆产生经济依赖及为台湾经济开拓新的增长点。其二，文献中对南向政策及新南向政策的内容及过程做了详细的阐述。其三，对于南向政策的实施效果，文献中通过相关新闻报道与资料分析做了说明；而对于新南向政策的实施效果，则有专家学者使用了更为严谨的计量方法进行了探究，但相关研究对数据变量的使用仍有缺乏，较为笼统。本文将会对上述文献中存在的不足进行重点论述和探究。
