# 结论与展望

## 主要结论

在本文中，我们分析了南向政策和新南向政策前后台湾进出口及对投资相关变量的比重变化。伴随着台湾产业结构的演变，台湾进出口及投资逐渐形成从美国和日本向中国大陆和东盟国家转移的趋势。忧心于中国大陆对台湾经济强大的吸引力，台湾当局最终在不同时期推行了南向政策与新南向政策，促进台湾经济重心向南亚、东南亚及大洋洲地区南移。在南向政策后期，政策受到了东南亚金融危机的冲击而大打折扣。对于新南向政策，一些实证研究表明其没有作用。即使在两次南向时期，台湾对南向国家的进出口及投资的数额与占比均有不同程度的提升，但本文从进出口及投资的比例分布角度入手，认为这种提升不能归功于政策的实施，而和贸易伙伴与台湾当局的“外交关系”、贸易伙伴国内生产总值、贸易伙伴经济开放度与实际有效汇率等因素有关。相反，作为对比，对于海峡两岸签署的ECFA协议，则对台湾的出口占比、进口占比对台投资占比和双边贸易额占比都有比较显著的正向提升作用。进出口提升的原因在于ECFA协议为海峡两岸的企业带来了丰厚的关税减免，这和南向政策与新南向政策不尽人意的实施效果形成了鲜明的反差。

另外我们发现，对于南向政策而言，贸易伙伴开放度的提升对出口占比、进口占比和双边贸易额占比具有正向显著的作用，贸易伙伴生产总值的提升对出口占比与双边贸易额占比具有显著正向的作用。从外交因素出发，与台湾是否具有“外交关系”对出口占比、进口占比、双边贸易额占比具有显著的负向作用，对投资占比具有显著的正向作用。对于海峡两岸签署的ECFA协议，则对台湾的出口占比、进口占比、双边贸易额占比和对台投资占比都有显著的正向作用。通过Wald检验，对于南向政策时期与新南向政策时期政策核心国家与非核心国家的政策作用效果，本文得出其统计上并无差异的结论。

台湾是贸易依存度较高的海岛型经济体，与外部国家或地区的贸易是其经济稳定发展的重要基础。从外部环境来看，东南亚及南亚国家对台湾有很强的贸易优势，这些国家人口较多，地理毗邻，具有突出的航运优势，经济发展的潜力较大。客观来说，台湾的经济成就，有一部分要归因于与这些国家或地区的贸易往来。但是同样应该看到，进入21世纪后，驱动台湾经济增长的最强动力无疑来自中国大陆。中国大陆拥有最为广阔的市场需求，同时为台企提供了优质的劳动力和稳定的营商环境。大陆签订了一系列客观上惠台的区域贸易协定，也是当代台湾经济发展的核心根本。尽管台湾当局试图阻碍这种以大陆为中心的经济增长模式，然而两次南向政策的实施，不仅未能实现当局所构想的贸易重心南迁，也未能成功使台湾的贸易与投资发展方向向着远离中国大陆的方向转移。

## 未来展望

新南向政策在可预期的未来仍会是台湾民进党当局重点实施的贸易政策，对政策的资助力度仍有可能会继续加强。尽管如此，由于新南向政策的本质背离了客观经济规律，属于使用政治力量干预客观经济，故其前景仍不容乐观。无论对于南向政策还是新南向政策，台湾当局都应摒弃远离大陆经济的指导思想，执行“大胆西进”而非“戒急用忍”，从而构建出一个真正自由的的经济秩序。只有如此才真正有利于台湾人民福祉，也有助于台湾走出长期经济停滞的局面。

对于大陆而言，一方面可以继续维护自己在东南亚地区的良好经济布局，维护“东盟加三”之良好格局，继续促进大陆与东盟十国、南亚六国、澳大利亚及新西兰之间的良好关系。另一方面，也应继续保持对台商投资的相关优惠条款，继续推行《海峡两岸经济合作框架协议》，促使两岸贸易发展，加速深化融合，确保海峡两岸的和平和繁荣。大陆对台湾的帮助有利于台湾融入与大陆共同构建的区域经济共同体中，进一步加强区域联结，为台湾经济的长期增长注入新的活力。两岸应共同努力加强经济交流和融合，努力奋斗，追求和平，致力振兴中华，这是当代海峡两岸炎黄子孙所不能回避的历史责任。
